### ISSUE TITLE
Preprocessing Step

### ISSUE THREAD

**Issue by MarceloContreras** [YuDongPan/DL_Classifier#1]
Hi :hand:, I would like to know your processig step in detail since I trying to replicate the same SSVEPformer results that you got (which match with the original paper). Did you consider any gaze shifting or visual delay in the signal? And Did you normalize the signal before or after applyting the bandpass filter?

**Comment by YuDongPan** [comment]
For calculating ITR, an extra 0.5 s for the gaze movement time was added into the parameter T. For this dataset in this repo, the estimated visual delay was 0.135 s. For the benchmark dataset, the estimated visual delay was 0.14 s. And we didn't use any normalization techinique to normalize the signal before or after appling the bandpass filter.

**Comment by MarceloContreras** [comment]
In other words, you process the data:

1. Skip the first 0.135 s (time delay) without considering gaze shifting (0.5 s).
2. Apply a bandpass filter

By any change, can you push the preprocessing script to replicate your data from the Nakanishi dataset?

**Comment by YuDongPan** [comment]
We preprocessed the original dataset using matlab. We removed first 38 sample points and skip 34 sample points (visual time delay), then used butterworth bandpass filter to filter the remaining data. For more details you could refer to https://github.com/mnakanishi/12JFPM_SSVEP.
